#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fossil
Version  : 2.15.2
Release  : 13
URL      : https://www.fossil-scm.org/home/uv/fossil-src-2.15.2.tar.gz
Source0  : https://www.fossil-scm.org/home/uv/fossil-src-2.15.2.tar.gz
Summary  : A simple, high-reliability, distributed software configuration management system
Group    : Development/Tools
License  : BSD-2-Clause BSL-1.0 GPL-2.0
Requires: fossil-bin = %{version}-%{release}
Requires: fossil-data = %{version}-%{release}
Requires: fossil-license = %{version}-%{release}
Requires: fossil-man = %{version}-%{release}
Requires: tcl
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pkgconfig(zlib)
BuildRequires : tcl

%description
Fossil is a simple, high-reliability, distributed software configuration management system.

%package bin
Summary: bin components for the fossil package.
Group: Binaries
Requires: fossil-data = %{version}-%{release}
Requires: fossil-license = %{version}-%{release}

%description bin
bin components for the fossil package.


%package data
Summary: data components for the fossil package.
Group: Data

%description data
data components for the fossil package.


%package license
Summary: license components for the fossil package.
Group: Default

%description license
license components for the fossil package.


%package man
Summary: man components for the fossil package.
Group: Default

%description man
man components for the fossil package.


%prep
%setup -q -n fossil-2.15.2
cd %{_builddir}/fossil-2.15.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1623799342
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
## make_prepend content
./configure --prefix=/usr --disable-internal-sqlite --json
## make_prepend end
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1623799342
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fossil
cp %{_builddir}/fossil-2.15.2/autosetup/LICENSE %{buildroot}/usr/share/package-licenses/fossil/34b2f1d7acba3eeb992e4281307640989cd08d0a
cp %{_builddir}/fossil-2.15.2/compat/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/fossil/892b34f7865d90a6f949f50d95e49625a10bc7f0
cp %{_builddir}/fossil-2.15.2/tools/cvs2fossil/doc/LICENSE %{buildroot}/usr/share/package-licenses/fossil/aede671429a0e8a5cc2fa35dfe5bcadd5c281b58
%make_install
## install_append content
install -Dm644 fossil.1 %{buildroot}/usr/share/man/man1/fossil.1
install -Dm644 tools/fossil-autocomplete.bash %{buildroot}/usr/share/bash-completion/completions/fossil
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fossil

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/fossil

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fossil/34b2f1d7acba3eeb992e4281307640989cd08d0a
/usr/share/package-licenses/fossil/892b34f7865d90a6f949f50d95e49625a10bc7f0
/usr/share/package-licenses/fossil/aede671429a0e8a5cc2fa35dfe5bcadd5c281b58

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fossil.1
