#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : fossil
Version  : 2.25
Release  : 17
URL      : https://fossil-scm.org/home/tarball/8f798279d5f7c3288099915f2ea88c57b6d6039f3f05eac5e237897af33376dc/fossil-src-2.25.tar.gz
Source0  : https://fossil-scm.org/home/tarball/8f798279d5f7c3288099915f2ea88c57b6d6039f3f05eac5e237897af33376dc/fossil-src-2.25.tar.gz
Summary  : A simple, high-reliability, distributed software configuration management system
Group    : Development/Tools
License  : BSD-2-Clause BSL-1.0 GPL-2.0 Zlib
Requires: fossil-bin = %{version}-%{release}
Requires: fossil-data = %{version}-%{release}
Requires: fossil-license = %{version}-%{release}
Requires: fossil-man = %{version}-%{release}
Requires: tcl
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pkgconfig(zlib)
BuildRequires : tcl
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Fossil is a simple, high-reliability, distributed software configuration management system.

%package bin
Summary: bin components for the fossil package.
Group: Binaries
Requires: fossil-data = %{version}-%{release}
Requires: fossil-license = %{version}-%{release}

%description bin
bin components for the fossil package.


%package data
Summary: data components for the fossil package.
Group: Data

%description data
data components for the fossil package.


%package license
Summary: license components for the fossil package.
Group: Default

%description license
license components for the fossil package.


%package man
Summary: man components for the fossil package.
Group: Default

%description man
man components for the fossil package.


%prep
%setup -q -n fossil-src-2.25
cd %{_builddir}/fossil-src-2.25
pushd ..
cp -a fossil-src-2.25 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740417010
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
## make_prepend content
./configure --prefix=/usr --disable-internal-sqlite --json
## make_prepend end
make  %{?_smp_mflags}

pushd ../buildavx2
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
## make_prepend content
./configure --prefix=/usr --disable-internal-sqlite --json
## make_prepend end
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1740417010
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fossil
cp %{_builddir}/fossil-src-%{version}/autosetup/LICENSE %{buildroot}/usr/share/package-licenses/fossil/34b2f1d7acba3eeb992e4281307640989cd08d0a || :
cp %{_builddir}/fossil-src-%{version}/compat/zlib/LICENSE %{buildroot}/usr/share/package-licenses/fossil/233f44af3fb55dcc7fddfef8e77ac627b0008756 || :
cp %{_builddir}/fossil-src-%{version}/compat/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/fossil/892b34f7865d90a6f949f50d95e49625a10bc7f0 || :
cp %{_builddir}/fossil-src-%{version}/tools/cvs2fossil/doc/LICENSE %{buildroot}/usr/share/package-licenses/fossil/aede671429a0e8a5cc2fa35dfe5bcadd5c281b58 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
## install_append content
install -Dm644 fossil.1 %{buildroot}/usr/share/man/man1/fossil.1
install -Dm644 tools/fossil-autocomplete.bash %{buildroot}/usr/share/bash-completion/completions/fossil
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/fossil
/usr/bin/fossil

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/fossil

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fossil/233f44af3fb55dcc7fddfef8e77ac627b0008756
/usr/share/package-licenses/fossil/34b2f1d7acba3eeb992e4281307640989cd08d0a
/usr/share/package-licenses/fossil/892b34f7865d90a6f949f50d95e49625a10bc7f0
/usr/share/package-licenses/fossil/aede671429a0e8a5cc2fa35dfe5bcadd5c281b58

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fossil.1
